### ISSUE TITLE
Add set-up documentation

### ISSUE THREAD

**Issue by sminnee** [mgax/SpaghettiFS#3]
It would be good if you could add a brief set-up guide for this system.
- Is there an installation script to run?
- What is the MacFuse command that you need to run to start it?
- How should the git repository be initialised?

**Comment by mgax** [comment]
I updated the readme file. Does it cover your questions?

**Comment by sminnee** [comment]
I don't see any changes... did you push to origin?

**Comment by mgax** [comment]
Yes, but for some reason github hasn't updated the front page. Look here: http://github.com/alex-morega/spaghettifs/tree/b4d8e5069169d3e174935fc28c64250d5ae7897a

**Comment by sminnee** [comment]
Cool, thanks.  Looks like github had a minor glitch - your README commit didn't appear on my homepage feed either (I watch your repos).

Anyway, the instructions are much better now.  I wasn't exactly sure what to do with fuse.py, so I put fuse.py into the spaghettifs directory next to filesystem.py, etc.  This appeared to let Python find the file, but I do have this issue:

```
Traceback (most recent call last):
  File "spaghettifs/tests/all.py", line 4, in <module>
    from test_filesystem import *
  File "/Users/sminnee/spaghettifs/spaghettifs/tests/test_filesystem.py", line 9, in <module>
    from spaghettifs.filesystem import repr_log
  File "/Users/sminnee/spaghettifs/spaghettifs/filesystem.py", line 7, in <module>
    from fuse import FUSE, Operations
  File "/Users/sminnee/spaghettifs/spaghettifs/fuse.py", line 212, in <module>
_libfuse = CDLL(_libfuse_path)
  File "/System/Library/Frameworks/Python.framework/Versions/2.6/lib/python2.6/ctypes/__i    nit__.py", line 345, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: dlopen(/usr/local/lib/libfuse.dylib, 6): Symbol not found: _iconv
  Referenced from: /usr/local/lib/libfuse.dylib
  Expected in: flat namespace
```

I'm running Snow Leopard.  Is this because I have missed an installation step, or is this a separate issue?

**Comment by mgax** [comment]
Eek, that looks nasty. Maybe you're using an outdated FUSE library? I'm running 2.0.3 with no problems, on Snow Leopard.

**Comment by sminnee** [comment]
I've seen people report this error on MacPorts bug trackers.  Not that I'm using MacPorts.  I think it might be a confusion of libiconv vs. iconv.

One suggestion: do you want to bundle a known working version of fuse.py into your codebase?  That would remove one potential place for problems to creep in, as well as simplifying the install process. :-)

**Comment by mgax** [comment]
I don't think I can do that. fuse.py is licensed GPL, SpaghettiFS is MIT. Anyway, I'd rather have it as a dependancy, like Dulwich.

**Comment by sminnee** [comment]
Well, if it could be easy_install'd then having it as a dependancy would make sense, but based on the comments on their issue tracker, fuse.py don't seem to be interested in doing this.  I read a comment along the lines of "It' just one file, why not bundle it with your app?" somewhere in a fuse.py bug report but I can't track down the link now.

It's licensed under BSD which is compatible with MIT, according to http://code.google.com/p/fusepy/

**Comment by sminnee** [comment]
Oh, here's the ticket where I saw them say that they couldn't be bothered packaging it:
http://code.google.com/p/fusepy/issues/detail?id=13

**Comment by mgax** [comment]
Hmm, you're right, it _is_ BSD. If the fuse.py developer doesn't make it work with easy_install (http://code.google.com/p/fusepy/issues/detail?id=22) then I'll probably include it at some point.
